#!/usr/bin/env python3

print("\nSetup Instructions for BRAKER3 with Singularity\n")
print("------------------------------------------------")

print("Dear BRAKER3 user,\n")
print("the following steps are required before you can run BRAKER3 with Singularity:\n")
print("  1) Please go to the website")
print("     http://topaz.gatech.edu/genemark/license_download.cgi")
print("     and download GeneMark-ETP (LINUX 64 kernel 2.6-4) after signing the")
print("     license agreement.\n")
print("  2) Place the two files (one *.tar.gz, and one called gm_key_64.gz) into your")
print("     home directory on the host where you want to execute the the container.")
print("     We will further refer to this as $HOME.\n")
print("  3) At the time of writing these instructions, the BRAKER3 authors do not know")
print("     the name of the archive file with GeneMark that you downloaded. Let's assume")
print("     it's called gmetp_linux_64.tar.gz. If this turns out to be incorrect, please")
print("     correct the name in when executing the following code in the host terminal:\n")
print("        cd ${HOME}")
print("        GM=gmetp_linux_64")
print("        tar -zxvf ${GM}.tar.gz")
print("        gunzip gm_key_64.gz")
print("        mv gm_key_64 ${HOME}/.gm_key")
print("\n\nYou are now ready to use the Singularity container for BRAKER3 with GeneMark-ETP.")
print("\n\nShould GeneMark-ETP not be available for download (yet) when you try this,")
print("please wait a few days and try, again.\n")
