#!/usr/bin/env python3

print("\nSetup Instructions for BRAKER3 with Singularity\n")
print("------------------------------------------------")

print("Dear BRAKER3 user,\n")
print("the following steps are required before you can run BRAKER3 with Singularity:\n")
print("  1) Please go to the website")
print("     https://github.com/gatech-genemark/GeneMark-ETP")
print("     and read the linked license agreement. You directly find the License text at:")
print("     https://github.com/gatech-genemark/GeneMark-ETP/blob/main/GeneMark_Software_License.txt")
print("     Only proceed if you agree to the license terms. If you are a commercial user or have ")
print("     other questions concerning this license, please contact Mark Bordovsky and Alexandre Lomsadze")
print("     at GeorgiaTech to inquire details (contact details at ")
print("     http://topaz.gatech.edu/genemark/contact.html\n")
print("  2) Download the license key (not the software) for  GeneMark-ES/ET/EP ver 4.71_lic , it's a file ")
print("     called gm_key_64.gz.")
print("  3) Unzip the file with:")
print("     gunzip gm_key_64.gz")
print("  4) Move the file to it's final location:")
print("     mv gm_key_64 ~/.gm_key")
print("You are now ready to use the Singularity container for BRAKER3 with GeneMark-ETP.")
